trigger:
  - main

pool:
  vmImage: 'windows-2019'

variables:
  azureServiceConnection: 'Visual Studio Enterprise Subscription – MPN'

stages:
- stage: My_first_stage
  displayName: Move Files Test
  jobs:
  - job: My_first_job
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI - Login'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Comando para crear el grupo de recursos
          az storage blob upload --account-name "versionstorageaks" --account-key "vIF4oI4vCk3qkPhFDkRph9YQ+f+Ja9pCRFmVdQwJ1a1+uh6lOPFrGj3LW3VBRGIwEb7TiDKVmzVh+AStsbB6jQ==" --type "$(Build.SourcesDirectory)/archivo_test.txt"