trigger:
  - main  # Cambiar "main" por la rama que deseas que active la pipeline

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  displayName: 'Ejecutar script de PowerShell'
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hola Mundo"'