trigger:
  - none

pr:
  - none

resources:
- repo: self

pool:
  vmImage: 'windows-2019'

variables:
- group: Test-Proyect-ScalingDta

stages:
- stage: My_first_stage
  displayName: Move Files Test
  jobs:
  - job: My_first_job
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI - Login'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          Write-Host "Script initializing"
          .\$(Build.SourcesDirectory)\resourcegroup.ps1
          