trigger:
  - none

pr:
  - none

resources:
- repo: self

pool:
  vmImage: 'windows-2019'

variables:
- group: Test-Proyect-ScalingDta
- functionCode: 'FLaDq4EwIbEagd2uF8EVvB34TUQ4VuUxWgtv9UT-0JLHAzFu0tEQwA=='

stages:
- stage: My_first_stage
  displayName: Move Files Test
  jobs:
  - job: My_first_job
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI - Login'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          Write-Host "Script initializing"
          $(Build.SourcesDirectory)\resourcegroup.ps1
- stage: POST_and_ConfigmapUpdater
  displayName: Create the post to the MavimtestURL
  jobs:
  - job: do_the_post_to_MavimtestURL
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI - Login'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $version = Get-Content -Path $(Build_SourcesDirectory)/version  
          $jsonBody = Get-Content -Path "$(Build.SourcesDirectory)/template_post.json"

          Write-Host "The Post body will be $jsonBody"
          Write-host "Function Code is this = " $(functionCode)
          # Doing a POST called
          # $response = Invoke-RestMethod -Uri "https://function-mavimtest.azurewebsites.net/api/GetWebConfig?code=$(functionCode)" -Method POST -Body $jsonBody -ContentType 'application/json'

          # Show the response
          Write-Host "Response from the POST request:"
          Write-Host $response          