trigger:
  - main  # Cambiar "main" por la rama que deseas que active la pipeline

pool:
  vmImage: 'windows-2019'

stages:
- stage: My first stage
  displayName: Move Files Test
  jobs:
  - job: My first job
    steps:
    - task: PowerShell@2
      displayName: My first task.
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Test Pipeline"