trigger:
  - main  # Cambiar "main" por la rama que deseas que active la pipeline

variables:
  azureServiceConnection: 'Visual Studio Enterprise Subscription – MPN'

pool:
  vmImage: 'windows-2019'

stages:
- stage: My_first_stage
  displayName: Move Files Test
  jobs:
  - job: My_first_job
    steps:
    - task: PowerShell@2
      displayName: My first task.
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Test Pipeline"
          az group create --name "MiGrupoDeRecursos" --location "East US" --subscription $(azureServiceConnection)