trigger:
  - main

pool:
  vmImage: 'windows-2019'

variables:
- group: Test-Proyect-ScalingDta
  azureServiceConnection: 'Visual Studio Enterprise Subscription – MPN'


stages:
- stage: My_first_stage
  displayName: Move Files Test
  jobs:
  - job: My_first_job
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI - Login'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #Expand the zip
          Expand-Archive -Path "$(Build.SourcesDirectory)/Web.zip" -DestinationPath "./WebExpanded" -Force

          #Get the version
          $version = Get-Content -Path $(Build.SourcesDirectory)/version                         
          Write-Host "The version is going to deploy is $version"

          #Rename the file with the specific name
          ls ".\WebExpanded\web.config"       
          Rename-Item -Path ".\WebExpanded\web.config" -NewName "web.config_$version"

          # Comando para crear el grupo de recursos
          az storage blob upload --connection-string "$(webconfigStorageAccount)" --type block --file "./WebExpanded/web.config_$version" --container-name webconfig --name web.config_$version --overwrite